-- Format for overwriting define values:
--
-- NDefines.NDiplomacy.MAX_CLIENT_STATES = 20

NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 10
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MONTHS = 24
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.IMPERIAL_REFORM_COST = 70
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -20
NDefines.NCountry.BREAK_MARRIAGE_PRESTIGE_PENALTY = -30
NDefines.NCountry.BREAK_MARRIAGE_STABILITY_PENALTY = 0
NDefines.NMilitary.MIN_MONTHLY_MANPOWER = 0.2
NDefines.NCountry.NAT_FOCUS_DECREASE = -3
NDefines.NCountry.NAT_FOCUS_INCREASE = 5
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.LAND_FORCELIMIT_EXTRA_COST_FACTOR = 3
NDefines.NCountry.LIBERTY_DESIRE_GREAT_POWER_VASSAL = 20
NDefines.NAI.ARTILLERY_FRACTION = 0.20
NDefines.NMilitary.WARGOAL_MAX_BONUS = 50
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1
NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 20.0
NGovernment.CENTRALIZE_STATE_ADM_COST = 75
NGovernment.EXPAND_INFRASTRUCTURE_ADM_COST = 60
NGovernment.CENTRALIZE_STATE_YEARS = 2